### PR TITLE
Fix #61 support AES GCM 128 / 192 JWE decryption

### LINKED ISSUE #61: [REQ] Support A128GCM and other A GCM encryption method
### Is your feature request related to a problem? Please describe.

While trying to implement network token checkout API as described here:

https://developer.mastercard.com/src/documentation/integration/server_integration/checkout/

We realized that the response payload coming from the MasterCard sandbox API server is using A128GCM algorithm for `encryptedPayload` encryption.

And currently that doesn't seem to be supported by this library, we got an error raised from here

https://github.com/Mastercard/client-encryption-java/blob/c090d68047de1dceee74ef245a398dfed6b90a06/src/main/java/com/mastercard/developer/encryption/jwe/JweObject.java#L52

### Describe the solution you'd like

Support A128GCM and other A-GCM encryption methods

### Describe alternatives you've considered
N/A

### Additional context
N/A

### PR DESCRIPTION
**Pull request by fangpenlin**
### PR checklist

- [x] An issue/feature request has been created for this PR
- [x] Pull Request title clearly describes the work in the pull request and the Pull Request description provides details about how to validate the work. Missing information here may result in a delayed response.
- [x] File the PR against the `main` branch
- [x] The code in this PR is covered by unit tests

#### Description
Add support for AES GCM 128 / 192 JWE decryption

### CODE REVIEW

**Comment by fangpenlin** [comment]
I just rebased this PR, @danny-gallagher could you please review it when you have time? thanks :pray:

**Comment by danny-gallagher** [comment]
> I just rebased this PR, @danny-gallagher could you please review it when you have time? thanks 🙏

Hi @fangpenlin, thank you for creating the PR! Everything looks good except one of the tests seem to be failing.

**Comment by fangpenlin** [comment]
@danny-gallagher sure, looking into it :eyes:

**Comment by fangpenlin** [comment]
@danny-gallagher I've already fixed the broken test. Could you please review it again, thank you so much :pray:

**Pull request merged**
